### ISSUE TITLE
Revise logic for handling keys and columns

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/diff-table#6]
@aaron0browne Assigning you to either document and/or implement the logic we discussed the other day. The question is either allowing a column map _or_ simply not allowing key columns with different names.

@murphyke Please share your thoughts as well.

**Comment by gracecodes144** [comment]
OK, so, I'm willing to put in some time for a column map feature. As a first idea of implementation I would add a `Rename` function to the `Table` interface which would allow changing a column name. The user would pass column maps via a `-rename` argument in the form `"foo:bar,baz:qux"` and `Rename` would be called on `t1` (changing the old table column names to match the new table column names) for each passed map at [line 207 in `main.go`](https://github.com/chop-dbhi/diff-table/blob/master/cmd/diff-table/main.go#L207). Thoughts?

**Comment by gracecodes144** [comment]
@bruth Does the above implementation plan make sense to you? Should I write up the code changes?

**Comment by bruth** [comment]
Hm. Yea that may work. It is in some ways a pre-processing step, so configuration was my first thought rather than adding it as an interface method. But give the implementation a shot which will at least implement the mapping logic and then we will see if the interface method makes sense.

**Comment by gracecodes144** [comment]
Fixed by #8
